//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appEjercicio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_f
    {
        public int idNota { get; set; }
        public int idAlumno { get; set; }
        public int idAsignacion { get; set; }
        public int idBimestre { get; set; }
        public int notaFinal { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual asignacion_materia asignacion_materia { get; set; }
        public virtual bimestre bimestre { get; set; }
    }
}
